apiVersion: v1
kind: Service
metadata:
  name: kubearmor-kibana
  namespace: kubearmor
spec:
  type: NodePort
  selector:
    kubearmor-app: kubearmor-kibana
  ports:
  - name: kibana-5601
    port: 5601
    targetPort: 5601
    nodePort: 30561
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-kibana
  namespace: kubearmor
  labels:
    kubearmor-app: kubearmor-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-kibana
  template:
    metadata:
      labels:
         kubearmor-app: kubearmor-kibana
      annotations:
        kubearmor-policy: audited
    spec:
      containers:
      - name: kubearmor-kibana
        image: elastic/kibana:6.8.6
        command: [ "/bin/bash", "-c", "/usr/share/kibana/bin/kibana-plugin remove x-pack; /usr/local/bin/kibana-docker" ]
        env:
        - name: CLUSTER_NAME
          value: "Default"
        - name: ELASTIC_SEARCH_URL
          value: "http://kubearmor-elasticsearch:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "admin"
        - name: ELASTICSEARCH_PASSWORD
          value: "password"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_ML_ENABLED
          value: "false"
        - name: XPACK_GRAPH_ENABLED
          value: "false"
        - name: XPACK_REPORTING_ENABLED
          value: "false"
        - name: XPACK_GROKDEBUGGER_ENABLED
          value: "false"
        ports:
        - containerPort: 5601
