apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearmor-logstash-configmap
  namespace: kubearmor
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "kubearmor-kafka-cluster-kafka-bootstrap.kubearmor.svc:9092"
        topics => [ "kubearmor-messages", "kubearmor-alerts", "kubearmor-syslogs" ]
        enable_auto_commit => "true"
        auto_offset_reset => "latest"
        consumer_threads => 4
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => "kubearmor-elasticsearch.kubearmor.svc:9200"
        user => "admin"
        password => "password"
        index => "kubearmor-%{+YYYYMMDD}"
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: kubearmor-logstash
  namespace: kubearmor
spec:
  selector:
    kubearmor-app: kubearmor-logstash
  ports:
  - name: ls-5000
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-logstash
  namespace: kubearmor
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-logstash
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-logstash
      annotations:
        kubearmor-policy: audited
    spec:
      containers:
      - name: kubearmor-logstash
        image: docker.elastic.co/logstash/logstash:5.6.0
        ports:
        - containerPort: 5000
        env:
        - name: PATH_CONFIG
          value: "/usr/share/logstash/pipeline"
        - name: HTTP_HOST
          value: "0.0.0.0"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        volumeMounts:
        - name: kubearmor-logstash-pipeline-volume
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: kubearmor-logstash-pipeline-volume
        configMap:
          name: kubearmor-logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
