{
 "title": "KubeArmor-Alerts DashBoard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Alert Metric",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(NamespaceName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | NamespaceName != `` | NamespaceName != `` | NamespaceName != `Unknown` | PolicyName != `` [5m]))"
    }
   ]
  },
  {
   "title": "Policy And Action Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Action, Policy) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | NamespaceName != `` | Action != `` [5m]))"
    }
   ]
  },
  {
   "title": "Alert from Different Pods",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(ContainerName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | ContainerName != `` | ContainerName != `Unknown` | Action != `` | PolicyName != `` [5m]))"
    }
   ]
  },
  {
   "title": "Alert from Different Namespace",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(NamespaceName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | NamespaceName != `` | NamespaceName != `Unknown` [5m]))"
    }
   ]
  },
  {
   "title": "Namespace and Severity Summary",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Severity, NamespaceName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | Severity != `` | NamespaceName != `` | NamespaceName != `Unknown` [5m]))"
    }
   ]
  },
  {
   "title": "Policy and Namespace Summary",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(PolicyName, NamespaceName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | PolicyName != `` | NamespaceName != `` | NamespaceName != `Unknown` [5m]))"
    }
   ]
  },
  {
   "title": "Namespace And Operation Summary",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Operation, NamespaceName) (rate({exporter=\"OTLP\"} != `cert` != `opentelemetry` | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\" | NamespaceName != `` | NamespaceName != `Unknown` | PolicyName != `` [5m]))"
    }
   ]
  },
  {
   "title": "Logs ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json ClusterName=\"body.ClusterName\", ContainerID=\"body.ContainerID\", ContainerImage=\"body.ContainerImage\", ContainerName=\"body.ContainerName\", Data=\"body.Data\", HostName=\"body.HostName\", HostPID=\"body.HostPID\", HostPPID=\"body.HostPPID\", Labels=\"body.Labels\", NamespaceName=\"body.NamespaceName\", Operation=\"body.Operation\", PID=\"body.PID\", PPID=\"body.PPID\", ParentProcessName=\"body.ParentProcessName\", PodName=\"body.PodName\", ProcessName=\"body.ProcessName\", Resource=\"body.Resource\", Result=\"body.Result\", Source=\"body.Source\", Type=\"body.Type\", UID=\"body.UID\", UpdatedTime=\"body.UpdatedTime\", Timestamp=\"body.Timestamp\", PolicyName=\"body.PolicyName\", Severity=\"body.Severity\", Message=\"body.Message\", Enforcer=\"body.Enforcer\", Action=\"body.Action\"\n"
    }
   ]
  }
 ]
}